services:
  - type: web
    name: playhaven
    env: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playhaven_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    
databases:
  - name: playhaven_db
    databaseName: playhaven
    user: playhaven
    plan: free 