version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ../.env.prod
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env.prod
    ports:
      - "5432:5432"

volumes:
  postgres_data: 