version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ../:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/playhaven
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playhaven
    ports:
      - "5432:5432"

volumes:
  postgres_data: 