"""empty message

Revision ID: 0af9de60a0f5
Revises: c06647e120c8
Create Date: 2025-01-26 19:59:45.174237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af9de60a0f5'
down_revision = 'c06647e120c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chat_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chat_association', schema=None) as batch_op:
        batch_op.drop_column('last_read_at')

    # ### end Alembic commands ###
