"""empty message

Revision ID: 3fef780b23b3
Revises: 5a8fe3ff7a94
Create Date: 2025-01-16 00:57:16.353055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fef780b23b3'
down_revision = '5a8fe3ff7a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_message_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_column('last_message_timestamp')
        batch_op.drop_column('last_message')

    # ### end Alembic commands ###
