"""empty message

Revision ID: c06647e120c8
Revises: b9f9a787bbf6
Create Date: 2025-01-21 12:46:04.667173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06647e120c8'
down_revision = 'b9f9a787bbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
